title: Walking Machine
email: walkingmachine@gmail.com
twitter_username: WM_ETS
github_username: wmets
CDN_url: http://wcdn.walkingmachine.ca
theme: minima
jekyll-mentions:
  base_url: https://twitter.com
exclude: ['README.md','CNAME','vendor','Gemfile','Gemfile.lock']
markdown: kramdown
street: 1100 rue Notre-Dame Ouest, Montreal, QC, H3C 1K3
phone: "+1-514-396-8800 #7408"
room:
  FR: "D-2014"
  EN: "D-2014"
gems:
  - jekyll-feed
  - jemoji

collections:
  photo_gallery:
      allemagne:

t:
  EN:
    donate:
        name: "Donate"
        url: "https://www.imakeanonlinedonation.org/fdets/campaign/ets/equipes/Teams/view/87d37b89-8571-4bf5-b4a9-051de1f6dc7a?OrgName=fdets"
    about:
      name: "About"
      url: "/en/about"
      sub_m:
        team:
          name: "Our team"
          url: "/en/team"
        project:
          name: "Project"
          url: "/en/project"
        partener:
          name: "Partner"
          url: "/en/partner"
        who:
          name: "Who we are"
          url: "/en/about"
    comp:
      name: "Competition"
      url: "/en/competition"
    blog:
      name: "Blog"
      url: "/en/blog"
    media:
      name: "Media"
      url: "/en/media"
    publication:
      name: "Publications"
      url: "/en/publications"
    contact:
      name: "Contact-us"
      url: "/en/contact"
  FR:
    donate:
        name: "Faire un don"
        url: "https://www.jedonneenligne.org/fdets/campagne/ets/equipes/Teams/view/87d37b89-8571-4bf5-b4a9-051de1f6dc7a"
    about:
      name: "À propos"
      url: "/fr/about"
      sub_m:
        team:
          name: "Notre equipe"
          url: "/fr/team"
        project:
          name: "Nos projets"
          url: "/fr/project"
        partener:
          name: "Partenaires"
          url: "/fr/partner"
        who:
          name: "Qui nous sommes"
          url: "/fr/about"
    comp:
      name: "Compétition"
      url: "/fr/competition"
    blog:
      name: "Blog"
      url: "/fr/blog"
    media:
      name: "Média"
      url: "/fr/media"
    publication:
      name: "Publications"
      url: "/fr/publications"
    contact:
      name: "Nous contacter"
      url: "/fr/contact"
